CREATE TABLE IF NOT EXISTS survival_movement (
  identifier VARCHAR(64) NOT NULL PRIMARY KEY,
  stamina    FLOAT NOT NULL DEFAULT 100.0,
  oxygen     FLOAT NOT NULL DEFAULT 100.0,
  sprinting  TINYINT(1) NOT NULL DEFAULT 0,
  underwater TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
